name: CIIntegration
on:
 pull_request:
    branches: [master,develop]
  
 push:
    branches: [master,develop]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Uses node version
         uses: actions/setup-node@v1
         with: 
          node-version: "12.x"
       - run: npm ci
       - run: npm run format:write
         env:
          CI: true
       - name: Build Project
         if: github.event_name == 'push'
         run: npm run build
       - name: Deploy staging
         if: github.event_name == 'push'
         run: npx surge --project ./build --domain silent-apparatus.surge.sh
         env: 
           SURGE_LOGIN: {{ secrets.SURGE_LOGIN }}
           SURGE_TOKEN: {{ secrets.SURGE_TOKEN }}