name: CI_Integration
on:
 pull_request:
    branches: [develop]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: action/checkout@v2
       - name: Uses node version
         uses: actions/setup-node@v1
         with: 
          node-version: "12.x"
       - run: npm ci
       - run: npm run format:check
         env:
          CI: true

       